# Generated by Django 4.2.7 on 2023-12-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_node_edge_edge_unique_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='data',
            field=models.JSONField(),
        ),
    ]
