# Generated by Django 4.2.7 on 2023-12-19 18:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_node_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ban_end_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 20))]),
        ),
    ]
