# Generated by Django 4.2.7 on 2023-12-20 06:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_car_table_alter_edge_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ban_end_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 21))]),
        ),
    ]
